= Elijars

*Elijars* creates JPMS aware executable jars with dependencies.

The jars:

. Are *JPMS aware*.
** If application has a module descriptor -- `module-info.java`, then the `java -jar myjar.jar` command places application classes into a module.
See <<jpmsAwareness>>
** Otherwise it falls back to class path mode, and puts all classes and its dependencies into a custom `ClassLoader`
. *Include all dependencies*.
The Elijars project includes all dependencies into a _single_ jar, similar to Spring Boot

[[jpmsAwareness]]
== JPMS awareness

When one creates an executable `jar` with module descriptor.
All application classes are placed into unnamed module if it run using `java -jar` command.

Consider the following application -- link:elijars-demos/elijars-print-module-demo/[`elijars-print-module-demo`].

The application:

. Has a class with a `main` method -- link:elijars-demos/elijars-print-module-demo/src/main/java/com/caco3/elijarsdemo/printmodule/PrintModuleDemo.java[`PrintModuleDemo.java`].
The method prints the module, where the class belongs
. Has module descriptor -- link:elijars-demos/elijars-print-module-demo/src/main/java/module-info.java[`module-info.java`]
. And `pom.xml`

When its jar with `Main-Class` attribute specified built and run:

[source,bash]
----
$ ./mvnw clean package --projects elijars-demos/elijars-print-module-demo
$ java -jar elijars-demos/elijars-print-module-demo/target/elijars-print-module-demo-0.0.1-SNAPSHOT.jar
----

The output is:

[source]
----
PrintModuleDemo unnamed module @34033bd0
----

Unnamed module is not what might be expected.

On the other hand, when a jar is repackaged using the Elijars' maven pluigin:

[source,bash]
----
$ ./mvnw package --projects elijars-demos/elijars-print-module-demo -P compose-jar
$  java -jar elijars-demos/elijars-print-module-demo/target/elijars-print-module-demo-0.0.1-SNAPSHOT.jar
----

The output is:

[source]
----
PrintModuleDemo module com.caco3.elijarsdemo.printmodule
----

== Usage

=== If application is modular

If your application is modular, then make the class with the `main` method _readable_.
To do so either:

* add `exports` declaration for the package containing the class, for example:
+
[source,java]
.module-info.java
----
module com.caco3.elijarsdemo.printmodule {
    exports com.caco3.elijarsdemo.printmodule;
}
----

* `open` the module, for example:
+
[source,java]
.module-info.java
----
open module com.caco3.elijarsdemo.printmodule {
}
----

=== Maven

Add maven plugin to your build:

[source,xml]
----
<plugin>
    <groupId>com.caco3</groupId>
    <artifactId>elijars-maven-plugin</artifactId>
    <version>${revision}</version>
    <executions>
        <execution>
            <goals>
                <goal>compose</goal> <!--1-->
            </goals>
            <configuration>
                <mainClass>com.caco3.elijars.simpleapplication.Main</mainClass> <!--2-->
                <startModule>elijars.simpleapplication</startModule> <!--3-->
            </configuration>
        </execution>
    </executions>
</plugin>
----
<1> Enable `compose` goal of the plugin
<2> Specify the main class to launch
<3> Specify the main module name

== Use cases

=== Fat modular jar

Elijars can create modular fat jars with dependencies.
There is no need to supply dependencies in `--module-path` or `-classpath` to make them available to the application.
The plugin embeds the dependencies into the final jar.

==== Application with guava sample

The sample application is in the `elijars-samples/application-with-guava` directory.

. Depends on https://github.com/google/guava[Google Guava]
. Its the only one class -- link:elijars-samples/application-with-guava/src/main/java/com/caco3/elijars/guavaapplication/GuavaApplication.java[`GuavaApplication`]:
.. Uses `ListenableFuture` from Guava
.. Prints module names for `GuavaApplication` and `ListenableFuture`


===== Run application

To run the application build the project:

. In the root directory (`elijars`):
+
[source,shell script]
----
$ ./mvnw verify
----

. Run the jar
+
[source,shell script]
----
$ java -jar elijars-samples/application-with-guava/target/application-with-guava.jar
----

The output is:

[source,text]
----
Hello from ListenableFuture, my module = 'module elijars.guavaapplication', and the ListenableFuture's module = 'module com.google.common'
----

. The `GuavaApplication` class is in the `elijars.guavaapplication` module
. The `ListenableFuture` is in the Guava's module -- `com.google.common`
